spring:
  application:
    name: snow-server-eureka
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    enableSelfPreservation: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/